# Generated by Django 4.0.5 on 2022-06-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincategory',
            name='img',
            field=models.ImageField(null=True, upload_to='profile_pics/'),
        ),
    ]
