# Generated by Django 4.0.5 on 2022-06-22 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_userinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=100)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.pin')),
            ],
        ),
    ]
