# Generated by Django 4.0.5 on 2022-06-22 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_pinboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinboard',
            name='pin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.pin'),
        ),
    ]
