# Generated by Django 4.0.5 on 2022-06-24 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_boards_pinboards_delete_pinboard_boards_board_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavePin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.pin')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
