# Generated by Django 4.0.5 on 2022-06-27 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_pin_likes_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='likes',
        ),
        migrations.AddField(
            model_name='pin',
            name='likes',
            field=models.ManyToManyField(related_name='pin_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
