# Generated by Django 4.0.5 on 2022-06-28 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_comments_date_posted_subcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='posts.pin'),
        ),
        migrations.DeleteModel(
            name='SubComments',
        ),
    ]
