# Generated by Django 4.0.5 on 2022-06-28 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_comments_pin_delete_subcomments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='content',
            new_name='comment',
        ),
    ]
