# Generated by Django 4.0.5 on 2022-06-28 09:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_alter_comments_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 9, 18, 16, 222978, tzinfo=utc)),
        ),
    ]
