# Generated by Django 4.0.5 on 2022-06-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_alter_comments_pin_alter_pin_date_posted_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='is_follow',
            field=models.BooleanField(default=False),
        ),
    ]
