# Generated by Django 4.0.5 on 2022-07-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_pin_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
