# Generated by Django 4.0.5 on 2022-07-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_alter_pin_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pincategory',
            name='img',
        ),
    ]
