# Generated by Django 4.0.5 on 2022-06-09 09:08

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
